-- AssessMate Fresh Schema Reset
-- This script deletes all old tables and creates the optimized 5-agent workflow structure.

-- 1. DROP ALL OLD TABLES
DROP TABLE IF EXISTS learning_plans CASCADE;
DROP TABLE IF EXISTS learning_tasks CASCADE;
DROP TABLE IF EXISTS milestones CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS user_responses CASCADE;
DROP TABLE IF EXISTS assessments CASCADE;
DROP TABLE IF EXISTS journey_skill_snapshots CASCADE;
DROP TABLE IF EXISTS journey_intelligence CASCADE;
DROP TABLE IF EXISTS journeys CASCADE;
DROP TABLE IF EXISTS user_skills CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS skill_update_logs CASCADE;
DROP TABLE IF EXISTS skill_evaluations CASCADE;
DROP TABLE IF EXISTS skill_taxonomy CASCADE;
DROP TABLE IF EXISTS resumes CASCADE;
DROP TABLE IF EXISTS job_descriptions CASCADE;

-- 2. CREATE NEW TABLES FOR 5-AGENT WORKFLOW

-- Journeys: Analysis from Agents 1, 2, 3, 4
CREATE TABLE journeys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL, -- Supabase Auth User ID
    role_name TEXT NOT NULL,
    company_name TEXT,
    jd_text TEXT NOT NULL,
    resume_text TEXT NOT NULL,
    analysis_result JSONB, -- Skill analysis & Gap analysis
    company_context JSONB, -- Agent 2: Company/Industry research
    status TEXT DEFAULT 'analyzed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assignments: 20 dynamic questions generated by Agent 4
CREATE TABLE assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    journey_id UUID REFERENCES journeys(id) ON DELETE CASCADE,
    questions JSONB NOT NULL, -- Array of 20 questions
    score INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User Skills: Mastery levels updated after Assignment
CREATE TABLE user_skills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    skill_name TEXT NOT NULL,
    mastery_level INTEGER NOT NULL CHECK (mastery_level >= 1 AND mastery_level <= 10),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, skill_name)
);

-- Learning Plans: ReactFlow Graph from Agent 5
CREATE TABLE learning_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    journey_id UUID REFERENCES journeys(id) ON DELETE CASCADE,
    plan_data JSONB NOT NULL, -- ReactFlow nodes and edges
    time_constraint TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- This ensures users can only see their own data

ALTER TABLE journeys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own journeys" ON journeys FOR ALL USING (auth.uid() = user_id);

ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own assignments" ON assignments FOR ALL USING (
    EXISTS (SELECT 1 FROM journeys WHERE journeys.id = assignments.journey_id AND journeys.user_id = auth.uid())
);

ALTER TABLE user_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own skills" ON user_skills FOR ALL USING (auth.uid() = user_id);

ALTER TABLE learning_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own plans" ON learning_plans FOR ALL USING (
    EXISTS (SELECT 1 FROM journeys WHERE journeys.id = learning_plans.journey_id AND journeys.user_id = auth.uid())
);
