-- AssessMate Scalable Schema with Robust RLS & User Profiles
-- This script ensures multi-user support, scalability, and security.

-- 1. DROP ALL OLD TABLES (For a fresh start)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS learning_plans CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS journeys CASCADE;
DROP TABLE IF EXISTS user_skills CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 2. CREATE NEW TABLES FOR 5-AGENT WORKFLOW

-- Profiles: Automatically synced with Supabase Auth (Google Auth)
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Journeys: Analysis from Agents 1, 2, 3, 4
CREATE TABLE journeys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFAULT auth.uid(),
    role_name TEXT NOT NULL,
    company_name TEXT,
    jd_text TEXT NOT NULL,
    resume_text TEXT NOT NULL,
    analysis_result JSONB, -- Skill analysis & Gap analysis
    company_context JSONB, -- Agent 2: Company/Industry research
    status TEXT DEFAULT 'analyzed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assignments: 20 dynamic questions generated by Agent 4
CREATE TABLE assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    journey_id UUID NOT NULL REFERENCES journeys(id) ON DELETE CASCADE,
    questions JSONB NOT NULL, -- Array of 20 questions
    score INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User Skills: Mastery levels updated after Assignment
CREATE TABLE user_skills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFAULT auth.uid(),
    skill_name TEXT NOT NULL,
    mastery_level INTEGER NOT NULL CHECK (mastery_level >= 1 AND mastery_level <= 10),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, skill_name)
);

-- Learning Plans: ReactFlow Graph from Agent 5
CREATE TABLE learning_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    journey_id UUID NOT NULL REFERENCES journeys(id) ON DELETE CASCADE,
    plan_data JSONB NOT NULL, -- ReactFlow nodes and edges
    time_constraint TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. AUTO-PROFILE CREATION (Trigger for Google Auth)
-- This function runs whenever a new user signs up via Supabase/Google Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, email)
  VALUES (
    NEW.id, 
    NEW.raw_user_meta_data->>'full_name', 
    NEW.raw_user_meta_data->>'avatar_url',
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3.1 POPULATE PROFILES FOR EXISTING USERS (Run once)
INSERT INTO public.profiles (id, full_name, avatar_url, email)
SELECT 
    id, 
    raw_user_meta_data->>'full_name', 
    raw_user_meta_data->>'avatar_url',
    email
FROM auth.users
ON CONFLICT (id) DO NOTHING;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. ENABLE ROW LEVEL SECURITY (RLS)
-- This ensures users can ONLY see and manage their own data.

-- PROFILES RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profiles" ON profiles FOR UPDATE USING (auth.uid() = id);

-- JOURNEYS RLS
ALTER TABLE journeys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own journeys" ON journeys FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own journeys" ON journeys FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own journeys" ON journeys FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own journeys" ON journeys FOR DELETE USING (auth.uid() = user_id);

-- ASSIGNMENTS RLS (Linked via journey_id)
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own assignments" ON assignments FOR SELECT USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = assignments.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can insert their own assignments" ON assignments FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = assignments.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can update their own assignments" ON assignments FOR UPDATE USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = assignments.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can delete their own assignments" ON assignments FOR DELETE USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = assignments.journey_id AND journeys.user_id = auth.uid()));

-- USER_SKILLS RLS
ALTER TABLE user_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own skills" ON user_skills FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own skills" ON user_skills FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own skills" ON user_skills FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own skills" ON user_skills FOR DELETE USING (auth.uid() = user_id);

-- LEARNING_PLANS RLS (Linked via journey_id)
ALTER TABLE learning_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own plans" ON learning_plans FOR SELECT USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = learning_plans.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can insert their own plans" ON learning_plans FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = learning_plans.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can update their own plans" ON learning_plans FOR UPDATE USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = learning_plans.journey_id AND journeys.user_id = auth.uid()));
CREATE POLICY "Users can delete their own plans" ON learning_plans FOR DELETE USING (EXISTS (SELECT 1 FROM journeys WHERE journeys.id = learning_plans.journey_id AND journeys.user_id = auth.uid()));

-- 5. PERFORMANCE INDEXES (For Scalability)
CREATE INDEX idx_profiles_email ON profiles(email);
CREATE INDEX idx_journeys_user_id ON journeys(user_id);
CREATE INDEX idx_assignments_journey_id ON assignments(journey_id);
CREATE INDEX idx_user_skills_user_id ON user_skills(user_id);
CREATE INDEX idx_learning_plans_journey_id ON learning_plans(journey_id);
