package models

import "time"

// Journey represents a user's career preparation journey
type Journey struct {
	ID             string      `json:"id,omitempty"`
	UserID         string      `json:"user_id"`
	RoleName       string      `json:"role_name"`
	CompanyName    string      `json:"company_name"`
	JDText         string      `json:"jd_text"`
	ResumeText     string      `json:"resume_text"`
	AnalysisResult interface{} `json:"analysis_result"`
	CompanyContext interface{} `json:"company_context"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
}

// CompanyOutput represents the research output about a company and role
type CompanyOutput struct {
	Difficulty       string   `json:"difficulty"`
	InterviewFocus   []string `json:"interview_focus"`
	RoleExpectations []string `json:"role_expectations"`
	RoleAnalysis     string   `json:"role_analysis"`
	CompanyContext   string   `json:"company_context"`
	InterviewProcess []string `json:"interview_process"`
	RecommendedFocus []string `json:"recommended_focus"`
}

// JDOutput represents the skills extracted from a JD
type JDOutput struct {
	Skills             []JDSkill `json:"skills"`
	HiddenExpectations []string  `json:"hidden_expectations"`
}

type JDSkill struct {
	Name          string   `json:"name"`
	Importance    string   `json:"importance"`
	RequiredLevel int      `json:"required_level"`
	Areas         []string `json:"areas"`
}

// ResumeOutput represents the skills extracted from a resume
type ResumeOutput struct {
	Skills          []ResumeSkill `json:"skills"`
	ConfidenceScore float64       `json:"confidence_score"`
}

type ResumeSkill struct {
	Name           string            `json:"name"`
	EstimatedLevel int               `json:"estimated_level"`
	Evidence       string            `json:"evidence"`
	Depth          map[string]string `json:"depth"`
}

// FinalAnalysis represents the computed intelligence from backend
type FinalAnalysis struct {
	SkillAnalysis []SkillMatch        `json:"skill_analysis"`
	CriticalGaps  []string            `json:"critical_gaps"`
	FitScore      int                 `json:"fit_score"`
	Comprehensive ComprehensiveOutput `json:"comprehensive"`
}

type SkillMatch struct {
	Name           string            `json:"name"`
	RequiredLevel  int               `json:"required_level"`
	EstimatedLevel int               `json:"estimated_level"`
	Gap            int               `json:"gap"`
	Importance     string            `json:"importance"`
	Evidence       string            `json:"evidence"`
	Depth          map[string]string `json:"depth"`
}

// ComprehensiveOutput is the combined raw output of JD, Resume, and Company analysis
type ComprehensiveOutput struct {
	JD      JDOutput      `json:"jd"`
	Resume  ResumeOutput  `json:"resume"`
	Company CompanyOutput `json:"company"`
}

// AssessmentQuestion represents a single question in an assessment
type AssessmentQuestion struct {
	ID            string `json:"id"`
	QuestionText  string   `json:"question_text"`
	Type          string   `json:"type"`
	Difficulty    string   `json:"difficulty"`
	SkillName     string   `json:"skill_name"`
	Area          string   `json:"area"`
	Options       []string `json:"options,omitempty"`
	CorrectAnswer string   `json:"correct_answer"`
	Explanation   string   `json:"explanation"`
	EvaluationWeight int   `json:"evaluation_weight"`
}

// AssessmentAgentOutput is the list of questions generated by the agent
type AssessmentAgentOutput struct {
	Questions []AssessmentQuestion `json:"questions"`
}

// LearningPlanOutput represents the nodes and edges for the learning roadmap
type LearningPlanOutput struct {
	Nodes []RFNode `json:"nodes"`
	Edges []RFEdge `json:"edges"`
	Tasks []string `json:"tasks"`
}

type RFNode struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Position struct {
		X float64 `json:"x"`
		Y float64 `json:"y"`
	} `json:"position"`
	Data struct {
		Label string `json:"label"`
	} `json:"data"`
}

type RFEdge struct {
	ID     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
}
